# -*- coding: utf-8 -*-
"""Pyhton IA Score de Crédito dos Clientes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_GvgZ0PfPgFLhcqyXBmlc0XEL9E-2MT8

# Projeto Python IA: Inteligência Artificial e Previsões

### Case: Score de Crédito dos Clientes

Você foi contratado por um banco para conseguir definir o score de crédito dos clientes. Você precisa analisar todos os clientes do banco e, com base nessa análise, criar um modelo que consiga ler as informações do cliente e dizer automaticamente o score de crédito dele: Ruim, Ok, Bom

Arquivos da aula: https://drive.google.com/drive/folders/1FbDqVq4XLvU85VBlVIMJ73p9oOu6u2-J?usp=drive_link
"""

# Score de crédito do cliente
# Boa - Good
# Ok - Standard
# Ruim - Poor
# !pip install pandas scikit-learn

# Passo a Passo
# Passo 0: Entender o desafio e a empresa
# Passo 1: Importar a base de dados
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

tabela = pd.read_csv("clientes.csv")

display(tabela)

# Passo 2: Preparar a base de dados para a Inteligência Artificial (IA)
display(tabela.info())

# int -> número inteiro
# float -> número com casa decimal
# object -> texto

# LabelEncoder
from sklearn.preprocessing import LabelEncoder

# Profissão

# Cientista
# Mecânico
# Ator
# Pintor
# Motorista
# Engenheiro
# Pedreiro
# Maquinista
codificador_profissao = LabelEncoder()
tabela["profissao"] = codificador_profissao.fit_transform(tabela["profissao"])

# mix_credito
codificador_credito = LabelEncoder()
tabela["mix_credito"] = codificador_credito.fit_transform(tabela["mix_credito"])

# comportamento_pagamento
codificador_pagamento = LabelEncoder()
tabela["comportamento_pagamento"] = codificador_pagamento.fit_transform(tabela["comportamento_pagamento"])

# criando a variável codificador
codificador_score = LabelEncoder()
tabela["score_credito"] = codificador_score.fit_transform(tabela["score_credito"])

display(tabela.info())

# Separar as informações da base de dados para a inteligência artificial

# Separar em X e Y
# Y -> Quem eu quero prever (coluna score_credito)
y = tabela["score_credito"]
# X -> As outras colunas (todas as colunas que eu vou usar para fazer a previsão)
x = tabela.drop(columns=["score_credito", "id_cliente"])

# Separar em dados de treino e de teste
from sklearn.model_selection import train_test_split

x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.3)

# Passo 3: Criar o modelo de IA -> prever a nota de crédito

# Árvore de Decisão -> RandomForest
# Vizinhos Próximos -> KNN

# Importar o modelo
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

# Criar o modelo
modelo_arvoredecisao = RandomForestClassifier()
modelo_knn = KNeighborsClassifier()

# Treinar o modelo
modelo_arvoredecisao.fit(x_treino, y_treino)
modelo_knn.fit(x_treino, y_treino)

# Passo 4: Escolher o melhor modelo

# Previsões
previsao_arvoredecisao = modelo_arvoredecisao.predict(x_teste)
previsao_knn = modelo_knn.predict(x_teste)

# Acurácia
from sklearn.metrics import accuracy_score

display(accuracy_score(y_teste, previsao_arvoredecisao))
display(accuracy_score(y_teste, previsao_knn))

# Passo 5: Fazer novas previsões
# O melhor modelo é o de árvore de decisão

# Carregar novos clientes
tabela_novos_clientes = pd.read_csv("novos_clientes.csv")

# Aplicar os mesmos codificadores usados no treino
tabela_novos_clientes["profissao"] = codificador_profissao.transform(tabela_novos_clientes["profissao"])
tabela_novos_clientes["mix_credito"] = codificador_credito.transform(tabela_novos_clientes["mix_credito"])
tabela_novos_clientes["comportamento_pagamento"] = codificador_pagamento.transform(tabela_novos_clientes["comportamento_pagamento"])

# Fazer a previsão com o modelo de árvore de decisão
previsoes = modelo_arvoredecisao.predict(tabela_novos_clientes)

# Passo 6: Criar o DataFrame e traduzir os números para nomes
# (Certifique-se que a variável 'previsao' foi gerada no passo anterior)
df_final = pd.DataFrame(previsoes, columns=['Score'])

# Traduzindo 0, 1, 2 de volta para Good, Standard, Poor
df_final['Score'] = codificador_score.inverse_transform(df_final['Score'])

# Passo 7: Gráfico e Texto Explicativo
# Gerar o gráfico
plt.figure(figsize=(10, 5))
sns.set_style("whitegrid")
grafico = sns.countplot(data=df_final, x='Score', palette='viridis', hue='Score', legend=False)
plt.title('Distribuição de Score dos Novos Clientes', fontsize=14)
plt.show()

# --- Texto Explicativo ---
total_clientes = len(df_final)
contagem = df_final['Score'].value_counts()
percentual_bom = (contagem.get('Good', 0) / total_clientes) * 100

print(f"--- ANÁLISE DAS PREVISÕES ---")
print(f"O modelo analisou um total de {total_clientes} novos clientes.")
print(f"A categoria predominante foi: {contagem.idxmax()} com {contagem.max()} clientes.")
print(f"Cerca de {percentual_bom:.1f}% da nova base foi classificada como 'Good' (Bom Score).")
print("\nConclusão: Este resultado permite ao banco decidir quais clientes receberão")
print("ofertas de crédito imediato ou precisarão de uma análise manual mais rigorosa.")

